FROM registry.access.redhat.com/ubi8/openjdk-11:1.11

ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XshowSettings:vm"

LABEL BASE_IMAGE_2="registry.access.redhat.com/ubi8/openjdk-11:1.11"

ADD spark-operator/target/spark-operator-*.jar /spark-operator.jar

CMD ["/usr/bin/java", "-jar", "/spark-operator.jar"]
