kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-edit-resources
  labels:
    app: spark
    component: spark-operator
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "services", "configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "update", "watch", "patch"]
- apiGroups: ["", "route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["radanalytics.io/v1"]
  resources: ["SparkCluster","SparkApplication","SparkHistoryServer"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
